### ISSUE TITLE
0.10.9 broke it again

### ISSUE THREAD

**Issue by imkindaprogrammermyself** [Monstrofil/replays_unpack#19]
It seems the data is shifted again, probably just like the last time but I can't find what's causing it.

**Comment by imkindaprogrammermyself** [comment]
```python
    def onArenaStateReceived(self, avatar, arenaUniqueId, teamBuildTypeId, preBattlesInfo, playersStates,
                             observersState, buildingsInfo):
        self._arena_id = arenaUniqueId
        self._players.create_or_update_players(pickle.loads(playersStates))
```
This one throws an `UnicodeDecodeError` error but adding `encoding='latin1'` fixes it.

Also, could this be the new `id_property_map`?
```python
{0: 'accountDBID', 1: 'antiAbuseEnabled', 2: 'avatarId', 3: 'camouflageInfo', 4: 'clanColor', 5: 'clanID',
     6: 'clanTag', 7: 'crewParams', 8: 'dogTag', 9: 'fragsCount', 10: 'friendlyFireEnabled', 11: 'hTTKStatus', 12: 'id',
     13: 'invitationsEnabled', 14: 'isAbuser', 15: 'isAlive', 16: 'isBot', 17: 'isClientLoaded', 18: 'isConnected',
     19: 'isHidden', 20: 'isLeaver', 21: 'isOwn', 22: 'isPreBattleOwner', 23: 'isSpectator', 24: 'isTDamager',
     25: 'isTKiller', 26: 'isTShooter', 27: 'killedBuildingsCount', 28: 'maxHealth', 29: 'playerMode',
     30: 'preBattleIdOnStart', 31: 'preBattleSign', 32: 'prebattleId', 33: 'prebattleIndex', 34: 'realm',
     35: 'shipComponents', 36: 'shipConfig', 37: 'shipConfigDump', 38: 'shipGameData', 39: 'shipId', 40: 'shipParamsId',
     41: 'skinId', 42: 'teamId', 43: 'ttkStatus', 44: 'vehicleParams'}
```
I got those value from `getPlayersInfo()` on the [ModAPI](https://forum.worldofwarships.eu/topic/91869-modapi-documentation/).

**Comment by imkindaprogrammermyself** [comment]
This could be the new mapping. 
```python
id_property_map = {0: 'accountDBID', 1: 'antiAbuseEnabled', 2: 'avatarId', 3: 'camouflageInfo', 4: 'clanColor',
                   5: 'clanID', 6: 'clanTag', 7: 'crewParams', 8: 'dogTag', 9: 'fragsCount', 10: 'friendlyFireEnabled',
                   11: 'id', 12: 'invitationsEnabled', 13: 'isAbuser', 14: 'isAlive', 15: 'isBot', 16: 'isClientLoaded',
                   17: 'isConnected', 18: 'isHidden', 19: 'isLeaver', 20: 'isPreBattleOwner', 21: 'isTShooter',
                   22: 'killedBuildingsCount', 23: 'maxHealth', 24: 'name', 25: 'playerMode', 26: 'preBattleIdOnStart',
                   27: 'preBattleSign', 28: 'prebattleId', 29: 'realm', 30: 'shipComponents', 31: 'shipConfigDump',
                   32: 'shipId', 33: 'shipParamsId', 34: 'skinId', 35: 'teamId', 36: 'ttkStatus'}
```
I checked and it aligns perfectly fine.

**Comment by Monstrofil** [comment]
Wg updates that constants dict regulary.

Here's original one:
`>>> BWPersonality.PlayersInfo.gSharedPInfo.numMemberMap
{0: 'accountDBID', 1: 'antiAbuseEnabled', 2: 'avatarId', 3: 'camouflageInfo', 4: 'clanColor', 5: 'clanID', 6: 'clanTag', 7: 'crewParams', 8: 'dogTag', 9: 'fragsCount', 10: 'friendlyFireEnabled', 11: 'id', 12: 'invitationsEnabled', 13: 'isAbuser', 14: 'isAlive', 15: 'isBot', 16: 'isClientLoaded', 17: 'isConnected', 18: 'isHidden', 19: 'isLeaver', 20: 'isPreBattleOwner', 21: 'isTShooter', 22: 'killedBuildingsCount', 23: 'maxHealth', 24: 'name', 25: 'playerMode', 26: 'preBattleIdOnStart', 27: 'preBattleSign', 28: 'prebattleId', 29: 'realm', 30: 'shipComponents', 31: 'shipConfigDump', 32: 'shipId', 33: 'shipParamsId', 34: 'skinId', 35: 'teamId', 36: 'ttkStatus'}`
