### ISSUE TITLE
Error parsing 0.11.1 team mission

### ISSUE THREAD

**Issue by nickntg** [Monstrofil/replays_unpack#20]
I am attaching a team mission replay. Near as I can tell, a package fails to process early on and I wonder if this could be the problem.
[a.zip](https://github.com/Monstrofil/replays_unpack/files/8104675/a.zip)

**Comment by Monstrofil** [comment]
Thanks, I'll check it.

нд, 20 лют. 2022, 20:35 користувач Nick Bitounis ***@***.***>
пише:

**Comment by Monstrofil** [comment]
Solved in https://github.com/Monstrofil/replays_unpack/commit/8468b416b5284cb3ac0f7f671958818bfe90d75a.

Some extra headers need to be processed in user_type.

**Comment by nickntg** [comment]
Super, thank you!
