### ISSUE TITLE
How to get readable shipInfo from shipID

### ISSUE THREAD

**Issue by WuNein** [Monstrofil/replays_unpack#26]
vehicles show shipID in int, i didn't find any refenence/doc to convert ID to something like 'Des Moines'. 
```
vehicles": [{"shipId": 3740186416, "relation": 1, "id": xxxxx, "name": "xxx"}
```
Is there shipid refenence open to public?

**Comment by WuNein** [comment]
aslain mod have some shipid , but i doubt whether it is enough.
shiptree.xml
```
<ship shipid='4185896752' x='16' y='3' /> <!-- PGSA104_Rhein -->
<ship shipid='4183799600' x='16' y='5' /> <!-- PGSA106_Weser -->
<ship shipid='4181702448' x='16' y='7' /> <!-- PGSA108_Parseval -->
<ship shipid='4179605296' x='16' y='9' /> <!-- PGSA110_Manfred_Richthofen -->
```

**Comment by WuNein** [comment]
another problem is, the replay file didn't seem to record the player's path.
```
def _process_packet(self, packet):
        if isinstance(packet, Position):
```
The packet does not contain the path of the player himself.
12x12 game with 23 different `packet.entityId` appeared.

**Comment by Monstrofil** [comment]
> vehicles show shipID in int, i didn't find any refenence/doc to convert ID to something like 'Des Moines'.
> 
> ```
> vehicles": [{"shipId": 3740186416, "relation": 1, "id": xxxxx, "name": "xxx"}
> ```
> 
> Is there shipid refenence open to public?

Check out the WG PAPI https://developers.wargaming.net/reference/all/wows/encyclopedia/ships/?application_id=be3e454f976a3dfa4ad34603bbb303f0&r_realm=eu&run=1
![image](https://user-images.githubusercontent.com/8678392/220296470-e9ac463a-87d6-49d1-be30-d7c7a97a427b.png)

Another option is to read GameParams content https://github.com/Monstrofil/game_params_wows.

**Comment by Monstrofil** [comment]
> The packet does not contain the path of the player himself.
PlayerPosition is what you are looking for.
https://github.com/Monstrofil/replays_unpack/blob/2734d6ea6e4a78fc92dfc9c6039275049b77c83a/replay_unpack/clients/wows/network/packets/__init__.py#L16
