### ISSUE TITLE
problem with parsing replay file

### ISSUE THREAD

**Issue by meepmoop200** [Monstrofil/replays_unpack#29]
Im using this command:
python replay_parser.py --replay replay6609.wowsreplay --strict_mode --raw_data_output replay6609
and its not working, i.e. the output is still illegible, other than some header info.

I installed it from the directory with pip, and I cant import the package in a new file because of the "-" in the package name...

**Comment by meepmoop200** [comment]
nvm, starting to get it, uncommented the lines in player.py and the output is wonderful.  Im sure Ill figre it out, thank you for making this

**Comment by Monstrofil** [comment]
@meepmoop200 publish some details once you figure it out so I can fix or document that stuff.
